// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comm/packages.proto

/*
Package comm is a generated protocol buffer package.

It is generated from these files:
	comm/packages.proto

It has these top-level messages:
	Envelope
	TimeSyncRequest
	TimeSyncResponse
	QueueChunkRequest
	PingMessage
	PongMessage
	SetVolumeRequest
	SubscribeChannelRequest
	NewSongInfo
	ChunkInfo
*/
package comm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Channel int32

const (
	Channel_AUDIO  Channel = 0
	Channel_META   Channel = 1
	Channel_LYRICS Channel = 2
)

var Channel_name = map[int32]string{
	0: "AUDIO",
	1: "META",
	2: "LYRICS",
}
var Channel_value = map[string]int32{
	"AUDIO":  0,
	"META":   1,
	"LYRICS": 2,
}

func (x Channel) String() string {
	return proto.EnumName(Channel_name, int32(x))
}
func (Channel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Envelope struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Envelope) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Envelope) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TimeSyncRequest struct {
	ClientSend int64 `protobuf:"varint,1,opt,name=clientSend" json:"clientSend,omitempty"`
}

func (m *TimeSyncRequest) Reset()                    { *m = TimeSyncRequest{} }
func (m *TimeSyncRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeSyncRequest) ProtoMessage()               {}
func (*TimeSyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimeSyncRequest) GetClientSend() int64 {
	if m != nil {
		return m.ClientSend
	}
	return 0
}

type TimeSyncResponse struct {
	ClientSendTime int64 `protobuf:"varint,1,opt,name=clientSendTime" json:"clientSendTime,omitempty"`
	ServerRecvTime int64 `protobuf:"varint,2,opt,name=serverRecvTime" json:"serverRecvTime,omitempty"`
	ServerSendTime int64 `protobuf:"varint,3,opt,name=serverSendTime" json:"serverSendTime,omitempty"`
}

func (m *TimeSyncResponse) Reset()                    { *m = TimeSyncResponse{} }
func (m *TimeSyncResponse) String() string            { return proto.CompactTextString(m) }
func (*TimeSyncResponse) ProtoMessage()               {}
func (*TimeSyncResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TimeSyncResponse) GetClientSendTime() int64 {
	if m != nil {
		return m.ClientSendTime
	}
	return 0
}

func (m *TimeSyncResponse) GetServerRecvTime() int64 {
	if m != nil {
		return m.ServerRecvTime
	}
	return 0
}

func (m *TimeSyncResponse) GetServerSendTime() int64 {
	if m != nil {
		return m.ServerSendTime
	}
	return 0
}

type QueueChunkRequest struct {
	StartTime        int64     `protobuf:"varint,1,opt,name=startTime" json:"startTime,omitempty"`
	ChunkId          int64     `protobuf:"varint,2,opt,name=chunkId" json:"chunkId,omitempty"`
	SampleLow        []float64 `protobuf:"fixed64,3,rep,packed,name=sampleLow" json:"sampleLow,omitempty"`
	SampleHigh       []float64 `protobuf:"fixed64,4,rep,packed,name=sampleHigh" json:"sampleHigh,omitempty"`
	FirstSampleIndex uint64    `protobuf:"varint,5,opt,name=firstSampleIndex" json:"firstSampleIndex,omitempty"`
}

func (m *QueueChunkRequest) Reset()                    { *m = QueueChunkRequest{} }
func (m *QueueChunkRequest) String() string            { return proto.CompactTextString(m) }
func (*QueueChunkRequest) ProtoMessage()               {}
func (*QueueChunkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueueChunkRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *QueueChunkRequest) GetChunkId() int64 {
	if m != nil {
		return m.ChunkId
	}
	return 0
}

func (m *QueueChunkRequest) GetSampleLow() []float64 {
	if m != nil {
		return m.SampleLow
	}
	return nil
}

func (m *QueueChunkRequest) GetSampleHigh() []float64 {
	if m != nil {
		return m.SampleHigh
	}
	return nil
}

func (m *QueueChunkRequest) GetFirstSampleIndex() uint64 {
	if m != nil {
		return m.FirstSampleIndex
	}
	return 0
}

type PingMessage struct {
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PongMessage struct {
}

func (m *PongMessage) Reset()                    { *m = PongMessage{} }
func (m *PongMessage) String() string            { return proto.CompactTextString(m) }
func (*PongMessage) ProtoMessage()               {}
func (*PongMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SetVolumeRequest struct {
	Volume float64 `protobuf:"fixed64,1,opt,name=volume" json:"volume,omitempty"`
}

func (m *SetVolumeRequest) Reset()                    { *m = SetVolumeRequest{} }
func (m *SetVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetVolumeRequest) ProtoMessage()               {}
func (*SetVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetVolumeRequest) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type SubscribeChannelRequest struct {
	Channel Channel `protobuf:"varint,1,opt,name=channel,enum=comm.Channel" json:"channel,omitempty"`
}

func (m *SubscribeChannelRequest) Reset()                    { *m = SubscribeChannelRequest{} }
func (m *SubscribeChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeChannelRequest) ProtoMessage()               {}
func (*SubscribeChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SubscribeChannelRequest) GetChannel() Channel {
	if m != nil {
		return m.Channel
	}
	return Channel_AUDIO
}

type NewSongInfo struct {
	FirstSampleOfSongIndex uint64 `protobuf:"varint,1,opt,name=firstSampleOfSongIndex" json:"firstSampleOfSongIndex,omitempty"`
	SongFileName           string `protobuf:"bytes,2,opt,name=songFileName" json:"songFileName,omitempty"`
}

func (m *NewSongInfo) Reset()                    { *m = NewSongInfo{} }
func (m *NewSongInfo) String() string            { return proto.CompactTextString(m) }
func (*NewSongInfo) ProtoMessage()               {}
func (*NewSongInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NewSongInfo) GetFirstSampleOfSongIndex() uint64 {
	if m != nil {
		return m.FirstSampleOfSongIndex
	}
	return 0
}

func (m *NewSongInfo) GetSongFileName() string {
	if m != nil {
		return m.SongFileName
	}
	return ""
}

type ChunkInfo struct {
	StartTime        int64  `protobuf:"varint,1,opt,name=startTime" json:"startTime,omitempty"`
	FirstSampleIndex uint64 `protobuf:"varint,2,opt,name=firstSampleIndex" json:"firstSampleIndex,omitempty"`
	ChunkSize        uint64 `protobuf:"varint,3,opt,name=chunkSize" json:"chunkSize,omitempty"`
}

func (m *ChunkInfo) Reset()                    { *m = ChunkInfo{} }
func (m *ChunkInfo) String() string            { return proto.CompactTextString(m) }
func (*ChunkInfo) ProtoMessage()               {}
func (*ChunkInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ChunkInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ChunkInfo) GetFirstSampleIndex() uint64 {
	if m != nil {
		return m.FirstSampleIndex
	}
	return 0
}

func (m *ChunkInfo) GetChunkSize() uint64 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Envelope)(nil), "comm.Envelope")
	proto.RegisterType((*TimeSyncRequest)(nil), "comm.TimeSyncRequest")
	proto.RegisterType((*TimeSyncResponse)(nil), "comm.TimeSyncResponse")
	proto.RegisterType((*QueueChunkRequest)(nil), "comm.QueueChunkRequest")
	proto.RegisterType((*PingMessage)(nil), "comm.PingMessage")
	proto.RegisterType((*PongMessage)(nil), "comm.PongMessage")
	proto.RegisterType((*SetVolumeRequest)(nil), "comm.SetVolumeRequest")
	proto.RegisterType((*SubscribeChannelRequest)(nil), "comm.SubscribeChannelRequest")
	proto.RegisterType((*NewSongInfo)(nil), "comm.NewSongInfo")
	proto.RegisterType((*ChunkInfo)(nil), "comm.ChunkInfo")
	proto.RegisterEnum("comm.Channel", Channel_name, Channel_value)
}

func init() { proto.RegisterFile("comm/packages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x71, 0x9a, 0x75, 0xcb, 0xd9, 0x07, 0xc1, 0x48, 0x23, 0x17, 0x08, 0x45, 0xbe, 0x80,
	0xaa, 0x17, 0x45, 0x0c, 0x89, 0xfb, 0xad, 0x0c, 0x11, 0x69, 0x1f, 0xe0, 0x0c, 0x24, 0x2e, 0xd3,
	0xf4, 0x34, 0x8d, 0x96, 0xd8, 0x21, 0x4e, 0x3a, 0xc6, 0x23, 0xf0, 0x4e, 0xbc, 0x1b, 0xb2, 0x9b,
	0x2c, 0x19, 0x94, 0xdd, 0xf9, 0xfc, 0xce, 0xff, 0x1c, 0xfb, 0xef, 0x63, 0xc3, 0xd3, 0x58, 0xe6,
	0xf9, 0xeb, 0x22, 0x8a, 0xaf, 0xa3, 0x04, 0xd5, 0xa4, 0x28, 0x65, 0x25, 0xa9, 0xad, 0x21, 0x3b,
	0x82, 0x9d, 0x53, 0xb1, 0xc2, 0x4c, 0x16, 0x48, 0x29, 0xd8, 0xd5, 0x6d, 0x81, 0x1e, 0xf1, 0xc9,
	0xc8, 0xe1, 0x66, 0xad, 0xd9, 0x3c, 0xaa, 0x22, 0xcf, 0xf2, 0xc9, 0x68, 0x8f, 0x9b, 0x35, 0x7b,
	0x03, 0x8f, 0xaf, 0xd2, 0x1c, 0xc3, 0x5b, 0x11, 0x73, 0xfc, 0x5e, 0xa3, 0xaa, 0xe8, 0x0b, 0x80,
	0x38, 0x4b, 0x51, 0x54, 0x21, 0x8a, 0xb9, 0x69, 0x30, 0xe0, 0x3d, 0xc2, 0x7e, 0x11, 0x70, 0xbb,
	0x1a, 0x55, 0x48, 0xa1, 0x90, 0xbe, 0x84, 0x83, 0x4e, 0xa2, 0xb3, 0x4d, 0xe1, 0x5f, 0x54, 0xeb,
	0x14, 0x96, 0x2b, 0x2c, 0x39, 0xc6, 0x2b, 0xa3, 0xb3, 0xd6, 0xba, 0xfb, 0xb4, 0xd3, 0xdd, 0xf5,
	0x1b, 0xf4, 0x75, 0x2d, 0x65, 0xbf, 0x09, 0x3c, 0xf9, 0x5c, 0x63, 0x8d, 0xd3, 0x65, 0x2d, 0xae,
	0x5b, 0x0b, 0xcf, 0xc1, 0x51, 0x55, 0x54, 0x56, 0xbd, 0x83, 0x74, 0x80, 0x7a, 0xb0, 0x1d, 0x6b,
	0x75, 0x30, 0x6f, 0x36, 0x6f, 0x43, 0xea, 0x83, 0xa3, 0xa2, 0xbc, 0xc8, 0xf0, 0x4c, 0xde, 0x78,
	0x03, 0x7f, 0x30, 0x22, 0x27, 0x96, 0x4b, 0x78, 0x07, 0x29, 0x03, 0x58, 0x07, 0x1f, 0xd3, 0x64,
	0xe9, 0xd9, 0x77, 0x92, 0x1e, 0xa5, 0x63, 0x70, 0x17, 0x69, 0xa9, 0xaa, 0xd0, 0xa0, 0x40, 0xcc,
	0xf1, 0x87, 0xb7, 0xe5, 0x93, 0x91, 0xcd, 0xff, 0xe1, 0x6c, 0x1f, 0x76, 0x3f, 0xa5, 0x22, 0x39,
	0x47, 0xa5, 0xa2, 0x04, 0x4d, 0x28, 0xbb, 0x70, 0x0c, 0x6e, 0x88, 0xd5, 0x57, 0x99, 0xd5, 0x39,
	0xb6, 0xde, 0x0e, 0x61, 0xb8, 0x32, 0xc0, 0x18, 0x23, 0xbc, 0x89, 0xd8, 0x09, 0x3c, 0x0b, 0xeb,
	0x99, 0x8a, 0xcb, 0x74, 0x86, 0xd3, 0x65, 0x24, 0x04, 0x66, 0x6d, 0xc9, 0x2b, 0x6d, 0xd8, 0x10,
	0x53, 0x73, 0x70, 0xb4, 0x3f, 0xd1, 0x0f, 0x66, 0xd2, 0xca, 0xda, 0x2c, 0x4b, 0x61, 0xf7, 0x02,
	0x6f, 0x42, 0x29, 0x92, 0x40, 0x2c, 0x24, 0x7d, 0x07, 0x87, 0xbd, 0x03, 0x5f, 0x2e, 0xd6, 0x09,
	0x6d, 0x87, 0x18, 0x3b, 0xff, 0xc9, 0x52, 0x06, 0x7b, 0x4a, 0x8a, 0xe4, 0x43, 0x9a, 0xe1, 0x45,
	0xd4, 0x8c, 0xd8, 0xe1, 0xf7, 0x18, 0x53, 0xe0, 0x98, 0x91, 0x99, 0x8d, 0x1e, 0x9e, 0xd7, 0xa6,
	0xfb, 0xb4, 0x36, 0xdf, 0xa7, 0xee, 0x64, 0x86, 0x19, 0xa6, 0x3f, 0xd7, 0x4f, 0xc6, 0xe6, 0x1d,
	0x18, 0x8f, 0x61, 0xbb, 0xf1, 0x4c, 0x1d, 0xd8, 0x3a, 0xfe, 0xf2, 0x3e, 0xb8, 0x74, 0x1f, 0xd1,
	0x1d, 0xb0, 0xcf, 0x4f, 0xaf, 0x8e, 0x5d, 0x42, 0x01, 0x86, 0x67, 0xdf, 0x78, 0x30, 0x0d, 0x5d,
	0x6b, 0x36, 0x34, 0x5f, 0xeb, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x6a, 0x70, 0x55,
	0x71, 0x03, 0x00, 0x00,
}
