version: "2"

exclude_patterns:
- '**/*.pb.go'
- 'ssh/parser/shell_parser/'
- 'util/_file_lister_test_files/'

plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true

checks:
  method-complexity:
    config:
      threshold: 8

  method-lines:
    config:
      threshold: 30
